# Test file generated by GenAI Test Generator
# Source file: app.py
# Framework: flask

import pytest
from flask import json


from app import index, create, edit, delete, get

import pytest
from unittest.mock import patch
from app import app

@pytest.fixture
def client():
    app.config['TESTING'] = True
    with app.test_client() as client:
        yield client

def test_index(client):
    response = client.get('/')
    assert response.status_code == 200

def test_create_get(client):
    response = client.get('/create')
    assert response.status_code == 200

@patch('app.random.randint', return_value=123)
def test_create_post(mock_randint, client):
    response = client.post('/create', data={'title': 'Test', 'content': 'Test'})
    assert response.status_code == 302
    assert mock_randint.called

def test_edit_get(client):
    response = client.get('/1/edit')
    assert response.status_code == 200

@patch('app.random.randint', return_value=456)
def test_edit_post(mock_randint, client):
    response = client.post('/1/edit', data={'title': 'Updated', 'content': 'Updated'})
    assert response.status_code == 302
    assert mock_randint.called

def test_delete(client):
    response = client.get('/1/delete')
    assert response.status_code == 302

def test_get_blog(client):
    response = client.get('/1')
    assert response.status_code == 200
